language: php
php:
  - '5.6'
env:
  - TEST_DIR=lib
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php-pear php5.6-dev libzmq-dev
script: cd $TEST_DIR &&
        printf "\n" | pecl install zmq-beta &&  
        echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"` &&
        composer install
